version: "3.5"
services: 
  api01: &api
    # image: zanfranceschi/rinha-api-2023
    build: ../ 
    hostname: code-api01
    environment:      
      - DB_CONNECTION_STRING__UsersDB=Data Source=/data/data.sqlite
      - ASPNETCORE_URLS=http://+:80;http://+:81- 
      - DOTNET_GCConserveMemory=1
      - DOTNET_gcServer=1
      - DOTNET_gcConcurrent=0
      - _DOTNET_GCHeapCount=0x1
      - _DOTNET_GCNoAffinitize=1
      - _DOTNET_GCHeapHardLimitPercent=0x10
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.9GB'
    volumes:
      - ./data:/data 
  api02:
    <<: *api
    hostname: code-api02
    environment:      
      - DB_CONNECTION_STRING__UsersDB=Data Source=/data/data.sqlite
      - ASPNETCORE_URLS=http://+:80;http://+:81
      - CACHE_CONNECTION_STRING=cache
      - HTTP_PORT=8081
    expose:
      - "80" 
    volumes:
      - ./data:/data 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
networks:
  default:
    driver: bridge
    name: rinha