version: "3.5"
services: 
  api01: &api
    # image: zanfranceschi/rinha-api-2023
    container_name: api01
    build: ../ 
    extra_hosts:
      - "host.docker.internal:host-gateway"    
    environment:      
      - ConnectionStrings__USERDB=Data Source=/data/data.sqlite
      - FileServiceOptions__FilePath=/data/dump_users.json 
      - ASPNETCORE_URLS=http://*:5001;http://*:5000
      - DOTNET_GCConserveMemory=1
      - DOTNET_gcServer=1
      - DOTNET_gcConcurrent=0
    expose:
      - "5000"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.3GB'
    volumes:
      - ./data:/data 
  api02:
    <<: *api
    container_name: api02
    volumes:
      - ./data:/data 
  proxy:
    container_name: proxy
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.2GB'
networks:
  default:
    driver: bridge
    name: codenetwork